name: tbco_conf_19
description: Event App for TBCÃ˜ Conference 2019


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^0.3.3+1
  flutter_platform_widgets: ^0.12.0
  scalable_image: ^1.1.2
  video_player: ^0.10.1+6
  url_launcher: ^5.1.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/images/seeley_circle.png
    - assets/images/tbco_circle.png
    - assets/images/madu_circle.png
    - assets/images/banning_circle.png
    - assets/images/johnson_circle.png
    - assets/images/henry+seeley.jpg
    - assets/images/banning.jpg
    - assets/images/robert.jpg
    - assets/images/darrell.jpg
    - assets/images/darrell.png
    - assets/images/tbco.jpg
    - assets/images/map.png
    - assets/images/sand.jpg
    - assets/images/menu_bg.jpg
    - assets/images/leadership.jpg
    - assets/images/talks.jpg
    - assets/images/register_background_r.jpg
    - assets/images/schedule_icon.png
    - assets/images/home_icon.png
    - assets/images/merch_icon.png
    - assets/images/sandc_icon.png
    - assets/images/map_icon.png
    - assets/images/guests_icon.png
    - assets/images/kids_icon.png
    - assets/images/talks_icon.png
    - assets/images/faq_icon.png
    - assets/images/photos_icon.png
    - assets/images/leadership_icon.png
    - assets/images/testimony_icon.png
    - assets/images/spotify.png
    - assets/images/apple.png
    - assets/images/tbcoMusic.png
    - assets/splash_vid.mp4

  fonts:
    - family: Respira
      fonts:
        - asset: assets/fonts/Respira-Black.ttf

    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-Hv.ttf
    - family: Helvetica-Bold
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-HvEx.ttf
    - family: Helvetica-Regular
      fonts:
        - asset: assets/fonts/HelveticaNeueLTCom-Ex.ttf


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
